# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj4Interrupt/Prj/mb_interrupt/mb_interrupt.srcs/sources_1/bd/mb_interrupt/ip/mb_interrupt_dlmb_v10_1/mb_interrupt_dlmb_v10_1.xci
# IP: The module: 'mb_interrupt_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj4Interrupt/Prj/mb_interrupt/mb_interrupt.srcs/sources_1/bd/mb_interrupt/ip/mb_interrupt_dlmb_v10_1/mb_interrupt_dlmb_v10_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_interrupt_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj4Interrupt/Prj/mb_interrupt/mb_interrupt.srcs/sources_1/bd/mb_interrupt/ip/mb_interrupt_dlmb_v10_1/mb_interrupt_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_interrupt_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj4Interrupt/Prj/mb_interrupt/mb_interrupt.srcs/sources_1/bd/mb_interrupt/ip/mb_interrupt_dlmb_v10_1/mb_interrupt_dlmb_v10_1.xci
# IP: The module: 'mb_interrupt_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj4Interrupt/Prj/mb_interrupt/mb_interrupt.srcs/sources_1/bd/mb_interrupt/ip/mb_interrupt_dlmb_v10_1/mb_interrupt_dlmb_v10_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_interrupt_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj4Interrupt/Prj/mb_interrupt/mb_interrupt.srcs/sources_1/bd/mb_interrupt/ip/mb_interrupt_dlmb_v10_1/mb_interrupt_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_interrupt_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
