# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_xbar_0/Mb_GpioRead_xbar_0.xci
# IP: The module: 'Mb_GpioRead_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_xbar_0/Mb_GpioRead_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mb_GpioRead_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_xbar_0/Mb_GpioRead_xbar_0.xci
# IP: The module: 'Mb_GpioRead_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_xbar_0/Mb_GpioRead_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mb_GpioRead_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
