# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj1Hello/Prj/Prj1Hello/Prj1Hello.srcs/sources_1/bd/Prj1Hello/ip/Prj1Hello_lmb_bram_1/Prj1Hello_lmb_bram_1.xci
# IP: The module: 'Prj1Hello_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj1Hello/Prj/Prj1Hello/Prj1Hello.srcs/sources_1/bd/Prj1Hello/ip/Prj1Hello_lmb_bram_1/Prj1Hello_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prj1Hello_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj1Hello/Prj/Prj1Hello/Prj1Hello.srcs/sources_1/bd/Prj1Hello/ip/Prj1Hello_lmb_bram_1/Prj1Hello_lmb_bram_1.xci
# IP: The module: 'Prj1Hello_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj1Hello/Prj/Prj1Hello/Prj1Hello.srcs/sources_1/bd/Prj1Hello/ip/Prj1Hello_lmb_bram_1/Prj1Hello_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prj1Hello_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
