# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/Code/xdc/xdcRead.xdc

# Block Designs: bd/Mb_GpioRead/Mb_GpioRead.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead || ORIG_REF_NAME==Mb_GpioRead}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_microblaze_0_0/Mb_GpioRead_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_microblaze_0_0 || ORIG_REF_NAME==Mb_GpioRead_microblaze_0_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_dlmb_v10_0/Mb_GpioRead_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_dlmb_v10_0 || ORIG_REF_NAME==Mb_GpioRead_dlmb_v10_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_ilmb_v10_0/Mb_GpioRead_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_ilmb_v10_0 || ORIG_REF_NAME==Mb_GpioRead_ilmb_v10_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_dlmb_bram_if_cntlr_0/Mb_GpioRead_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Mb_GpioRead_dlmb_bram_if_cntlr_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_ilmb_bram_if_cntlr_0/Mb_GpioRead_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Mb_GpioRead_ilmb_bram_if_cntlr_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_lmb_bram_0/Mb_GpioRead_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_lmb_bram_0 || ORIG_REF_NAME==Mb_GpioRead_lmb_bram_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_mdm_1_0/Mb_GpioRead_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_mdm_1_0 || ORIG_REF_NAME==Mb_GpioRead_mdm_1_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_clk_wiz_1_0/Mb_GpioRead_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_clk_wiz_1_0 || ORIG_REF_NAME==Mb_GpioRead_clk_wiz_1_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_rst_clk_wiz_1_100M_0/Mb_GpioRead_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Mb_GpioRead_rst_clk_wiz_1_100M_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_axi_gpio_0_0/Mb_GpioRead_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_axi_gpio_0_0 || ORIG_REF_NAME==Mb_GpioRead_axi_gpio_0_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_microblaze_0_axi_periph_0/Mb_GpioRead_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Mb_GpioRead_microblaze_0_axi_periph_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_axi_uartlite_0_0/Mb_GpioRead_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_axi_uartlite_0_0 || ORIG_REF_NAME==Mb_GpioRead_axi_uartlite_0_0}]

# IP: bd/Mb_GpioRead/ip/Mb_GpioRead_xbar_0/Mb_GpioRead_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_GpioRead_xbar_0 || ORIG_REF_NAME==Mb_GpioRead_xbar_0}]

# XDC: bd/Mb_GpioRead/Mb_GpioRead_ooc.xdc
