# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/ToolSoftWare/modulesim/win32
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.cache/wt [current_project]
set_property parent.project_path C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/hdl/Mb_GpioRead_wrapper.v
add_files C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/Mb_GpioRead.bd
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_microblaze_0_0/Mb_GpioRead_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_microblaze_0_0/Mb_GpioRead_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_microblaze_0_0/Mb_GpioRead_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_dlmb_v10_0/Mb_GpioRead_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_dlmb_v10_0/Mb_GpioRead_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_ilmb_v10_0/Mb_GpioRead_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_ilmb_v10_0/Mb_GpioRead_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_dlmb_bram_if_cntlr_0/Mb_GpioRead_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_ilmb_bram_if_cntlr_0/Mb_GpioRead_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_lmb_bram_0/Mb_GpioRead_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_mdm_1_0/Mb_GpioRead_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_mdm_1_0/Mb_GpioRead_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_clk_wiz_1_0/Mb_GpioRead_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_clk_wiz_1_0/Mb_GpioRead_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_clk_wiz_1_0/Mb_GpioRead_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_rst_clk_wiz_1_100M_0/Mb_GpioRead_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_rst_clk_wiz_1_100M_0/Mb_GpioRead_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_rst_clk_wiz_1_100M_0/Mb_GpioRead_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_axi_gpio_0_0/Mb_GpioRead_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_axi_gpio_0_0/Mb_GpioRead_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_axi_gpio_0_0/Mb_GpioRead_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_axi_uartlite_0_0/Mb_GpioRead_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_axi_uartlite_0_0/Mb_GpioRead_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_axi_uartlite_0_0/Mb_GpioRead_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/ip/Mb_GpioRead_xbar_0/Mb_GpioRead_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/Mb_GpioRead_ooc.xdc]
set_property is_locked true [get_files C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/Mb_GpioRead/Mb_GpioRead.srcs/sources_1/bd/Mb_GpioRead/Mb_GpioRead.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/Code/xdc/xdcRead.xdc
set_property used_in_implementation false [get_files C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/Code/xdc/xdcRead.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Mb_GpioRead_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Mb_GpioRead_wrapper.dcp

catch { report_utilization -file Mb_GpioRead_wrapper_utilization_synth.rpt -pb Mb_GpioRead_wrapper_utilization_synth.pb }
