# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mb_ddr/mb_ddr.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr || ORIG_REF_NAME==mb_ddr}]

# IP: bd/mb_ddr/ip/mb_ddr_microblaze_0_0/mb_ddr_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_microblaze_0_0 || ORIG_REF_NAME==mb_ddr_microblaze_0_0}]

# IP: bd/mb_ddr/ip/mb_ddr_dlmb_v10_0/mb_ddr_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_dlmb_v10_0 || ORIG_REF_NAME==mb_ddr_dlmb_v10_0}]

# IP: bd/mb_ddr/ip/mb_ddr_ilmb_v10_0/mb_ddr_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_ilmb_v10_0 || ORIG_REF_NAME==mb_ddr_ilmb_v10_0}]

# IP: bd/mb_ddr/ip/mb_ddr_dlmb_bram_if_cntlr_0/mb_ddr_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_ddr_dlmb_bram_if_cntlr_0}]

# IP: bd/mb_ddr/ip/mb_ddr_ilmb_bram_if_cntlr_0/mb_ddr_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_ddr_ilmb_bram_if_cntlr_0}]

# IP: bd/mb_ddr/ip/mb_ddr_lmb_bram_0/mb_ddr_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_lmb_bram_0 || ORIG_REF_NAME==mb_ddr_lmb_bram_0}]

# IP: bd/mb_ddr/ip/mb_ddr_mdm_1_0/mb_ddr_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_mdm_1_0 || ORIG_REF_NAME==mb_ddr_mdm_1_0}]

# IP: bd/mb_ddr/ip/mb_ddr_clk_wiz_1_0/mb_ddr_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_clk_wiz_1_0 || ORIG_REF_NAME==mb_ddr_clk_wiz_1_0}]

# IP: bd/mb_ddr/ip/mb_ddr_rst_clk_wiz_1_100M_0/mb_ddr_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_ddr_rst_clk_wiz_1_100M_0}]

# IP: bd/mb_ddr/ip/mb_ddr_axi_uartlite_0_0/mb_ddr_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_axi_uartlite_0_0 || ORIG_REF_NAME==mb_ddr_axi_uartlite_0_0}]

# IP: bd/mb_ddr/ip/mb_ddr_microblaze_0_axi_periph_0/mb_ddr_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_ddr_microblaze_0_axi_periph_0}]

# IP: bd/mb_ddr/ip/mb_ddr_mig_7series_0_0/mb_ddr_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_mig_7series_0_0 || ORIG_REF_NAME==mb_ddr_mig_7series_0_0}]

# IP: bd/mb_ddr/ip/mb_ddr_axi_mem_intercon_0/mb_ddr_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_axi_mem_intercon_0 || ORIG_REF_NAME==mb_ddr_axi_mem_intercon_0}]

# IP: bd/mb_ddr/ip/mb_ddr_xbar_0/mb_ddr_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_xbar_0 || ORIG_REF_NAME==mb_ddr_xbar_0}]

# IP: bd/mb_ddr/ip/mb_ddr_rst_mig_7series_0_81M_0/mb_ddr_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==mb_ddr_rst_mig_7series_0_81M_0}]

# IP: bd/mb_ddr/ip/mb_ddr_auto_cc_0/mb_ddr_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_auto_cc_0 || ORIG_REF_NAME==mb_ddr_auto_cc_0}]

# IP: bd/mb_ddr/ip/mb_ddr_auto_us_0/mb_ddr_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_auto_us_0 || ORIG_REF_NAME==mb_ddr_auto_us_0}]

# IP: bd/mb_ddr/ip/mb_ddr_auto_us_1/mb_ddr_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ddr_auto_us_1 || ORIG_REF_NAME==mb_ddr_auto_us_1}]

# XDC: bd/mb_ddr/mb_ddr_ooc.xdc
