# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj3Ddr2/Prj/mc_ddr2/mc_ddr2.srcs/sources_1/bd/mb_ddr/ip/mb_ddr_auto_cc_0/mb_ddr_auto_cc_0.xci
# IP: The module: 'mb_ddr_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj3Ddr2/Prj/mc_ddr2/mc_ddr2.srcs/sources_1/bd/mb_ddr/ip/mb_ddr_auto_cc_0/mb_ddr_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_ddr_auto_cc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj3Ddr2/Prj/mc_ddr2/mc_ddr2.srcs/sources_1/bd/mb_ddr/ip/mb_ddr_auto_cc_0/mb_ddr_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_ddr_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj3Ddr2/Prj/mc_ddr2/mc_ddr2.srcs/sources_1/bd/mb_ddr/ip/mb_ddr_auto_cc_0/mb_ddr_auto_cc_0.xci
# IP: The module: 'mb_ddr_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj3Ddr2/Prj/mc_ddr2/mc_ddr2.srcs/sources_1/bd/mb_ddr/ip/mb_ddr_auto_cc_0/mb_ddr_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_ddr_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj3Ddr2/Prj/mc_ddr2/mc_ddr2.srcs/sources_1/bd/mb_ddr/ip/mb_ddr_auto_cc_0/mb_ddr_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_ddr_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
