set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
set_property PACKAGE_PIN C4 [get_ports uart_rtl_rxd]
set_property PACKAGE_PIN D4 [get_ports uart_rtl_txd]
set_property IOSTANDARD LVCMOS33 [get_ports clock_rtl]
set_property PACKAGE_PIN E3 [get_ports clock_rtl]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]
set_property PACKAGE_PIN N17 [get_ports reset_rtl]
