# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mb_interrupt/mb_interrupt.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt || ORIG_REF_NAME==mb_interrupt}]

# IP: bd/mb_interrupt/ip/mb_interrupt_microblaze_0_1/mb_interrupt_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_microblaze_0_1 || ORIG_REF_NAME==mb_interrupt_microblaze_0_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_dlmb_v10_1/mb_interrupt_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_dlmb_v10_1 || ORIG_REF_NAME==mb_interrupt_dlmb_v10_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_ilmb_v10_1/mb_interrupt_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_ilmb_v10_1 || ORIG_REF_NAME==mb_interrupt_ilmb_v10_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_dlmb_bram_if_cntlr_1/mb_interrupt_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_interrupt_dlmb_bram_if_cntlr_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_ilmb_bram_if_cntlr_1/mb_interrupt_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_interrupt_ilmb_bram_if_cntlr_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_lmb_bram_1/mb_interrupt_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_lmb_bram_1 || ORIG_REF_NAME==mb_interrupt_lmb_bram_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_microblaze_0_axi_periph_1/mb_interrupt_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mb_interrupt_microblaze_0_axi_periph_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_microblaze_0_axi_intc_1/mb_interrupt_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_microblaze_0_axi_intc_1 || ORIG_REF_NAME==mb_interrupt_microblaze_0_axi_intc_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_microblaze_0_xlconcat_1/mb_interrupt_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_microblaze_0_xlconcat_1 || ORIG_REF_NAME==mb_interrupt_microblaze_0_xlconcat_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_mdm_1_1/mb_interrupt_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_mdm_1_1 || ORIG_REF_NAME==mb_interrupt_mdm_1_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_clk_wiz_1_1/mb_interrupt_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_clk_wiz_1_1 || ORIG_REF_NAME==mb_interrupt_clk_wiz_1_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_rst_clk_wiz_1_100M_1/mb_interrupt_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_interrupt_rst_clk_wiz_1_100M_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_axi_uartlite_0_0/mb_interrupt_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_axi_uartlite_0_0 || ORIG_REF_NAME==mb_interrupt_axi_uartlite_0_0}]

# IP: bd/mb_interrupt/ip/mb_interrupt_xbar_1/mb_interrupt_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_xbar_1 || ORIG_REF_NAME==mb_interrupt_xbar_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_mig_7series_0_1/mb_interrupt_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_mig_7series_0_1 || ORIG_REF_NAME==mb_interrupt_mig_7series_0_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_axi_mem_intercon_0/mb_interrupt_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_axi_mem_intercon_0 || ORIG_REF_NAME==mb_interrupt_axi_mem_intercon_0}]

# IP: bd/mb_interrupt/ip/mb_interrupt_xbar_2/mb_interrupt_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_xbar_2 || ORIG_REF_NAME==mb_interrupt_xbar_2}]

# IP: bd/mb_interrupt/ip/mb_interrupt_rst_mig_7series_0_81M_1/mb_interrupt_rst_mig_7series_0_81M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_rst_mig_7series_0_81M_1 || ORIG_REF_NAME==mb_interrupt_rst_mig_7series_0_81M_1}]

# IP: bd/mb_interrupt/ip/mb_interrupt_axi_gpio_0_0/mb_interrupt_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_axi_gpio_0_0 || ORIG_REF_NAME==mb_interrupt_axi_gpio_0_0}]

# IP: bd/mb_interrupt/ip/mb_interrupt_axi_gpio_1_0/mb_interrupt_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_axi_gpio_1_0 || ORIG_REF_NAME==mb_interrupt_axi_gpio_1_0}]

# IP: bd/mb_interrupt/ip/mb_interrupt_auto_cc_0/mb_interrupt_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_auto_cc_0 || ORIG_REF_NAME==mb_interrupt_auto_cc_0}]

# IP: bd/mb_interrupt/ip/mb_interrupt_auto_us_0/mb_interrupt_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_auto_us_0 || ORIG_REF_NAME==mb_interrupt_auto_us_0}]

# IP: bd/mb_interrupt/ip/mb_interrupt_auto_us_1/mb_interrupt_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_interrupt_auto_us_1 || ORIG_REF_NAME==mb_interrupt_auto_us_1}]

# XDC: bd/mb_interrupt/mb_interrupt_ooc.xdc
