set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
set_property PACKAGE_PIN E3 [get_ports clk_in1]
set_property PACKAGE_PIN N17 [get_ports reset]
set_property PACKAGE_PIN C4 [get_ports uart_rtl_rxd]
set_property PACKAGE_PIN D4 [get_ports uart_rtl_txd]
set_property PACKAGE_PIN V11 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property PACKAGE_PIN V10 [get_ports {gpio_rtl_tri_io[0]}]
