webtalk_init -webtalk_dir C:\\Prj\\xilinxPrj\\MicroblazePrj\\Prj2AXIGpio\\Prj\\MBAXIGpio\\Mb_GpioRead\\Mb_GpioRead.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-08-10 13:32:42" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2b48n16g4268d2rb4fnfc7n2t3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.4_8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1533876375170" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.4" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1533876375170"
webtalk_add_data -client sdk -key uid -value "1533876510190" -context "sdk\\\\bsp/1533876510190"
webtalk_add_data -client sdk -key hwid -value "1533876375170" -context "sdk\\\\bsp/1533876510190"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1533876510190"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1533876510190"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1533876510190"
webtalk_add_data -client sdk -key uid -value "1533876511267" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key hwid -value "1533876375170" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key bspid -value "1533876510190" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key projSize -value "115.81640625" -context "sdk\\\\application/1533876511267"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1533882762977"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1533882762977"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1533882762977"
webtalk_add_data -client sdk -key DebugCount -value "14" -context "sdk\\\\bsp/1533882762977"
webtalk_add_data -client sdk -key PerfCount -value "1" -context "sdk\\\\bsp/1533882762977"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1533882762977"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1533882762977"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1533882762977"
webtalk_transmit -clientid 2232529858 -regid "" -xml C:\\Prj\\xilinxPrj\\MicroblazePrj\\Prj2AXIGpio\\Prj\\MBAXIGpio\\Mb_GpioRead\\Mb_GpioRead.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Prj\\xilinxPrj\\MicroblazePrj\\Prj2AXIGpio\\Prj\\MBAXIGpio\\Mb_GpioRead\\Mb_GpioRead.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Prj\\xilinxPrj\\MicroblazePrj\\Prj2AXIGpio\\Prj\\MBAXIGpio\\Mb_GpioRead\\Mb_GpioRead.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
