# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/Code/xdc/xdc.xdc

# Block Designs: bd/mb_sys_gpio/mb_sys_gpio.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio || ORIG_REF_NAME==mb_sys_gpio}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_microblaze_0_0/mb_sys_gpio_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_microblaze_0_0 || ORIG_REF_NAME==mb_sys_gpio_microblaze_0_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_dlmb_v10_0/mb_sys_gpio_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_dlmb_v10_0 || ORIG_REF_NAME==mb_sys_gpio_dlmb_v10_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_ilmb_v10_0/mb_sys_gpio_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_ilmb_v10_0 || ORIG_REF_NAME==mb_sys_gpio_ilmb_v10_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_dlmb_bram_if_cntlr_0/mb_sys_gpio_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_sys_gpio_dlmb_bram_if_cntlr_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_ilmb_bram_if_cntlr_0/mb_sys_gpio_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_sys_gpio_ilmb_bram_if_cntlr_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_lmb_bram_0/mb_sys_gpio_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_lmb_bram_0 || ORIG_REF_NAME==mb_sys_gpio_lmb_bram_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_mdm_1_0/mb_sys_gpio_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_mdm_1_0 || ORIG_REF_NAME==mb_sys_gpio_mdm_1_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_clk_wiz_1_0/mb_sys_gpio_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_clk_wiz_1_0 || ORIG_REF_NAME==mb_sys_gpio_clk_wiz_1_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_rst_clk_wiz_1_100M_0/mb_sys_gpio_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_sys_gpio_rst_clk_wiz_1_100M_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_axi_gpio_0_0/mb_sys_gpio_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_axi_gpio_0_0 || ORIG_REF_NAME==mb_sys_gpio_axi_gpio_0_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_microblaze_0_axi_periph_0/mb_sys_gpio_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_sys_gpio_microblaze_0_axi_periph_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_axi_uartlite_0_0/mb_sys_gpio_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_axi_uartlite_0_0 || ORIG_REF_NAME==mb_sys_gpio_axi_uartlite_0_0}]

# IP: bd/mb_sys_gpio/ip/mb_sys_gpio_xbar_0/mb_sys_gpio_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_sys_gpio_xbar_0 || ORIG_REF_NAME==mb_sys_gpio_xbar_0}]

# XDC: bd/mb_sys_gpio/mb_sys_gpio_ooc.xdc
