# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/MB_AXIGpio/MB_AXIGpio.srcs/sources_1/bd/mb_sys_gpio/ip/mb_sys_gpio_ilmb_bram_if_cntlr_0/mb_sys_gpio_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_sys_gpio_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/MB_AXIGpio/MB_AXIGpio.srcs/sources_1/bd/mb_sys_gpio/ip/mb_sys_gpio_ilmb_bram_if_cntlr_0/mb_sys_gpio_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_sys_gpio_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/MB_AXIGpio/MB_AXIGpio.srcs/sources_1/bd/mb_sys_gpio/ip/mb_sys_gpio_ilmb_bram_if_cntlr_0/mb_sys_gpio_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_sys_gpio_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Prj/xilinxPrj/MicroblazePrj/Prj2AXIGpio/Prj/MBAXIGpio/MB_AXIGpio/MB_AXIGpio.srcs/sources_1/bd/mb_sys_gpio/ip/mb_sys_gpio_ilmb_bram_if_cntlr_0/mb_sys_gpio_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_sys_gpio_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
