# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Prj/xilinxPrj/MicroblazePrj/Prj1Hello/Prj/src/constrain/mb_hello.xdc

# Block Designs: bd/Prj1Hello/Prj1Hello.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello || ORIG_REF_NAME==Prj1Hello}]

# IP: bd/Prj1Hello/ip/Prj1Hello_microblaze_0_1/Prj1Hello_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_microblaze_0_1 || ORIG_REF_NAME==Prj1Hello_microblaze_0_1}]

# IP: bd/Prj1Hello/ip/Prj1Hello_dlmb_v10_1/Prj1Hello_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_dlmb_v10_1 || ORIG_REF_NAME==Prj1Hello_dlmb_v10_1}]

# IP: bd/Prj1Hello/ip/Prj1Hello_ilmb_v10_1/Prj1Hello_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_ilmb_v10_1 || ORIG_REF_NAME==Prj1Hello_ilmb_v10_1}]

# IP: bd/Prj1Hello/ip/Prj1Hello_dlmb_bram_if_cntlr_1/Prj1Hello_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==Prj1Hello_dlmb_bram_if_cntlr_1}]

# IP: bd/Prj1Hello/ip/Prj1Hello_ilmb_bram_if_cntlr_1/Prj1Hello_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==Prj1Hello_ilmb_bram_if_cntlr_1}]

# IP: bd/Prj1Hello/ip/Prj1Hello_lmb_bram_1/Prj1Hello_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_lmb_bram_1 || ORIG_REF_NAME==Prj1Hello_lmb_bram_1}]

# IP: bd/Prj1Hello/ip/Prj1Hello_mdm_1_1/Prj1Hello_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_mdm_1_1 || ORIG_REF_NAME==Prj1Hello_mdm_1_1}]

# IP: bd/Prj1Hello/ip/Prj1Hello_clk_wiz_1_1/Prj1Hello_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_clk_wiz_1_1 || ORIG_REF_NAME==Prj1Hello_clk_wiz_1_1}]

# IP: bd/Prj1Hello/ip/Prj1Hello_rst_clk_wiz_1_100M_1/Prj1Hello_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==Prj1Hello_rst_clk_wiz_1_100M_1}]

# IP: bd/Prj1Hello/ip/Prj1Hello_axi_uartlite_0_0/Prj1Hello_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_axi_uartlite_0_0 || ORIG_REF_NAME==Prj1Hello_axi_uartlite_0_0}]

# IP: bd/Prj1Hello/ip/Prj1Hello_microblaze_0_axi_periph_1/Prj1Hello_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Prj1Hello_microblaze_0_axi_periph_1 || ORIG_REF_NAME==Prj1Hello_microblaze_0_axi_periph_1}]

# XDC: bd/Prj1Hello/Prj1Hello_ooc.xdc
